version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mwl
      POSTGRES_PASSWORD: mwl
      POSTGRES_DB: merge_with_label
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    image: ghcr.io/eun/merge-with-label:latest
    restart: unless-stopped
    command: "server"
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      PostgresDSN: "postgres://mwl:mwl@postgres:5432/merge_with_label?sslmode=disable"
    depends_on:
      - postgres

  worker:
    image: ghcr.io/eun/merge-with-label:latest
    restart: unless-stopped
    command: "worker"
    volumes:
      - "./private-key.pem:/private-key.pem:ro"
    environment:
      PostgresDSN: "postgres://mwl:mwl@postgres:5432/merge_with_label?sslmode=disable"
      APP_ID: <your app id>
      PRIVATE_KEY: /private-key.pem
    depends_on:
      - postgres
    deploy:
      replicas: 1

volumes:
  postgres_data:
