version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mwl
      POSTGRES_PASSWORD: mwl
      POSTGRES_DB: merge_with_label
    ports:
      - "5432:5432"

  server:
    build: .
    command: "server"
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      PostgresDSN: "postgres://mwl:mwl@postgres:5432/merge_with_label?sslmode=disable"
    depends_on:
      - postgres

  worker:
    build: .
    command: "worker"
    volumes:
      - "./private-key.pem:/private-key.pem:ro"
    environment:
      PostgresDSN: "postgres://mwl:mwl@postgres:5432/merge_with_label?sslmode=disable"
      APP_ID: <your app id>
      PRIVATE_KEY: /private-key.pem
    depends_on:
      - postgres
    deploy:
      replicas: 1
