version: '3.9'
services:
  postgres:
    image: supabase/postgres:17.6.1.151
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: supabase_admin
      POSTGRES_PASSWORD: mwl
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U supabase_admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    image: ghcr.io/eun/merge-with-label-server:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      PostgresDSN: "postgres://supabase_admin:mwl@postgres:5432/postgres?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12

  worker:
    image: ghcr.io/eun/merge-with-label-worker:latest
    restart: unless-stopped
    volumes:
      - "./private-key.pem:/private-key.pem:ro"
    environment:
      PostgresDSN: "postgres://supabase_admin:mwl@postgres:5432/postgres?sslmode=disable"
      APP_ID: <your app id>
      PRIVATE_KEY: /private-key.pem
    depends_on:
      postgres:
        condition: service_healthy
      server:
        condition: service_healthy
    deploy:
      replicas: 1
