# this workflow runs when a release was published.
on:
  release:
    types: [published]

name: "release_published"
jobs:
  # Build the binary using GoReleaser
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3.6.0
      -
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/eun/merge-with-label:latest,ghcr.io/eun/merge-with-label:${{ env.GITHUB_REF_SLUG }}
