# this workflow runs when a release was published.
on:
  release:
    types: [published]

name: "release_published"
jobs:
  # Build the binary using GoReleaser
  build_binary:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3.5.3
      -
        name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.6
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}
      -
        name: Login to Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/eun/merge-with-label:latest,ghcr.io/eun/merge-with-label:${{GITHUB_REF_SLUG}}
